/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vejoe_opencv_OpenCV */

#ifndef _Included_com_vejoe_opencv_OpenCV
#define _Included_com_vejoe_opencv_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vejoe_opencv_OpenCV
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vejoe_opencv_OpenCV_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_vejoe_opencv_OpenCV
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vejoe_opencv_OpenCV_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_vejoe_opencv_OpenCV
 * Method:    detectEyesDistance
 * Signature: ([BIIIFZ)F
 */
JNIEXPORT jfloat JNICALL Java_com_vejoe_opencv_OpenCV_detectEyesDistance
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jfloat, jboolean);

/*
 * Class:     com_vejoe_opencv_OpenCV
 * Method:    detectLines
 * Signature: ([BIIZ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_vejoe_opencv_OpenCV_detectLines
  (JNIEnv *, jobject, jbyteArray, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
